"use client";
import { ChevronLeft, ChevronRight, ExternalLink, X } from "lucide-react";
import { useContext, useMemo, useState } from "react";
import { OperationalTable, type OperationalRow } from "./OperationalTable";
import { AdminFilterTabs } from "./AdminFilterTabs";
import { StatePanel } from "@/components/feedback/StatePanel";
import { StatusBadge, type StatusBadgeTone } from "@/components/ui/StatusBadge";
import { Surface } from "@/components/ui/Surface";
import { PageSizeSelect } from "@/components/ui/PageSizeSelect";
import { LangSwitch, type Lang } from "@/context/LangSwitch";
import { translateBackendValue } from "@/lib/localization/backendEnum";
import { VEHICLE_DOCUMENT_STATUSES, type AdminVehicleDocument, type VehicleDocumentStatus, useAdminVehicleDocuments, useApproveVehicleDocument, useRejectVehicleDocument } from "@/queries/admin-vehicle-documents";
import { AdminConfirmModal } from "./AdminConfirmModal";

const messages: Record<Lang, Record<string, string>> = {
  uz: { table: "Avtomobil hujjatlari", status: "Holat", all: "Barcha holatlar", loading: "Hujjatlar yuklanmoqda", error: "Hujjatlarni yuklab bo‘lmadi", retry: "Qayta urinish", empty: "Hujjatlar topilmadi", details: "Hujjat tekshiruvi", close: "Yopish", vehicle: "Avtomobil", type: "Hujjat turi", file: "Faylni ko‘rish", noFile: "Fayl havolasi qaytarilmadi", approve: "Tasdiqlash", reject: "Rad etish", reason: "Rad etish sababi", placeholder: "Aniq sababni yozing", confirmApprove: "Hujjatni tasdiqlaysizmi?", confirmReject: "Hujjatni rad etasizmi?", cancel: "Bekor qilish", confirm: "Tasdiqlash", success: "Hujjat holati yangilandi.", actionError: "Amalni bajarib bo‘lmadi.", page: "Sahifa" },
  en: { table: "Vehicle documents", status: "Status", all: "All statuses", loading: "Loading documents", error: "Could not load documents", retry: "Try again", empty: "No documents found", details: "Document review", close: "Close", vehicle: "Vehicle", type: "Document type", file: "View file", noFile: "No file URL was returned", approve: "Approve", reject: "Reject", reason: "Rejection reason", placeholder: "Enter a clear reason", confirmApprove: "Approve this document?", confirmReject: "Reject this document?", cancel: "Cancel", confirm: "Confirm", success: "Document status updated.", actionError: "Could not complete the action.", page: "Page" },
  ru: { table: "Документы автомобилей", status: "Статус", all: "Все статусы", loading: "Загрузка документов", error: "Не удалось загрузить документы", retry: "Повторить", empty: "Документы не найдены", details: "Проверка документа", close: "Закрыть", vehicle: "Автомобиль", type: "Тип документа", file: "Открыть файл", noFile: "Ссылка на файл не получена", approve: "Одобрить", reject: "Отклонить", reason: "Причина отказа", placeholder: "Укажите точную причину", confirmApprove: "Одобрить документ?", confirmReject: "Отклонить документ?", cancel: "Отмена", confirm: "Подтвердить", success: "Статус документа обновлён.", actionError: "Не удалось выполнить действие.", page: "Страница" },
};
const tones: Record<string, StatusBadgeTone> = { PENDING: "warning", APPROVED: "success", REJECTED: "danger" };
const idOf = (doc: AdminVehicleDocument) => doc.documentId ?? doc.docId ?? doc.id;
const vehicleIdOf = (doc: AdminVehicleDocument) => doc.vehicleId ?? doc.vehicle?.vehicleId;
const titleOf = (doc: AdminVehicleDocument, vehicleLabel: string) => [doc.vehicle?.makeName, doc.vehicle?.modelName, doc.vehicle?.year].filter(Boolean).join(" ") || `${vehicleLabel} #${vehicleIdOf(doc) ?? "—"}`;
const urlOf = (doc: AdminVehicleDocument) => doc.fileUrl ?? doc.downloadUrl ?? doc.url;

export function AdminVehicleDocumentsWorkspace() {
  const { currentLang } = useContext(LangSwitch); const t = messages[currentLang];
  const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10); const [status, setStatus] = useState<VehicleDocumentStatus | "">("PENDING"); const [selectedId, setSelectedId] = useState<string | number | null>(null); const [decision, setDecision] = useState<"approve" | "reject" | null>(null); const [reason, setReason] = useState(""); const [feedback, setFeedback] = useState<"success" | "error" | "">("");
  const query = useAdminVehicleDocuments(page, pageSize, status); const approve = useApproveVehicleDocument(); const reject = useRejectVehicleDocument(); const pending = approve.isPending || reject.isPending;
  const selected = query.data?.list.find((doc) => String(idOf(doc)) === String(selectedId));
  const rows = useMemo<OperationalRow[]>(() => (query.data?.list ?? []).map((doc) => ({ id: `#${idOf(doc) ?? "—"}`, primary: titleOf(doc, t.vehicle), secondary: [translateBackendValue(doc.docType, currentLang), doc.fileName ?? doc.originalFileName].filter(Boolean).join(" · ") || "—", value: `#${vehicleIdOf(doc) ?? "—"}`, status: translateBackendValue(doc.status ?? "PENDING", currentLang), tone: tones[doc.status ?? "PENDING"] ?? "neutral" })), [currentLang, query.data, t.vehicle]);
  const statusTabs = [{ value: "", label: t.all, count: status === "" ? query.data?.elements ?? rows.length : rows.length }, ...VEHICLE_DOCUMENT_STATUSES.map((option) => ({ value: option, label: translateBackendValue(option, currentLang), count: status === option ? query.data?.elements ?? rows.length : rows.filter((row) => row.status === translateBackendValue(option, currentLang)).length, tone: tones[option] }))];
  const close = () => { setSelectedId(null); setDecision(null); setReason(""); };
  const confirm = async () => { if (!selectedId || !decision || (decision === "reject" && !reason.trim())) return; setFeedback(""); try { if (decision === "approve") await approve.mutateAsync(selectedId); else await reject.mutateAsync({ docId: selectedId, reason }); setFeedback("success"); close(); } catch { setFeedback("error"); } };
  return <div className="space-y-4">
    {feedback ? <StatusBadge tone={feedback === "success" ? "success" : "danger"}>{feedback === "success" ? t.success : t.actionError}</StatusBadge> : null}
    {query.isError ? (
      <StatePanel title={t.error} action={<button className="rounded-md bg-brand-navy-900 px-4 py-2 text-sm font-bold text-white" onClick={() => query.refetch()}>{t.retry}</button>} />
    ) : (
      <OperationalTable actionsDisabled={pending} label={t.table} loading={query.isLoading} rows={rows} onOpen={(row) => { setSelectedId(row.id.replace(/^#/, "")); setDecision(null); setReason(""); }} toolbarControls={<AdminFilterTabs ariaLabel={t.status} disabled={pending} value={status} onChange={(value) => { setStatus(value as VehicleDocumentStatus | ""); setPage(0); close(); }} options={statusTabs} />} />
    )}
    {query.data?.list.length ? <div className="flex flex-wrap items-center justify-end gap-3"><PageSizeSelect disabled={query.isLoading} value={pageSize} onChange={(size) => { setPageSize(size); setPage(0); }} /><button className="rounded-md border p-2 disabled:opacity-40" disabled={!page} onClick={() => setPage(page - 1)}><ChevronLeft /></button><span className="text-sm font-bold">{t.page} {page + 1} / {query.data.pages || 1}</span><button className="rounded-md border p-2 disabled:opacity-40" disabled={page + 1 >= (query.data.pages || 1)} onClick={() => setPage(page + 1)}><ChevronRight /></button></div> : null}
    {selected ? <div className="fixed inset-0 z-50 grid place-items-center bg-brand-navy-950/65 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget && !pending) close(); }} role="presentation"><Surface aria-modal="true" className="w-full max-w-2xl shadow-2xl" role="dialog"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-brand-gold-text">{t.details}</p><h2 className="mt-2 text-xl font-black">{titleOf(selected, t.vehicle)}</h2></div><button aria-label={t.close} className="grid size-11 place-items-center rounded-md border" disabled={pending} onClick={close}><X /></button></div><dl className="mt-5 grid gap-4 border-t pt-5 sm:grid-cols-3"><div><dt className="text-xs font-bold text-text-secondary">{t.type}</dt><dd className="mt-1 font-bold">{translateBackendValue(selected.docType, currentLang)}</dd></div><div><dt className="text-xs font-bold text-text-secondary">{t.status}</dt><dd className="mt-1"><StatusBadge tone={tones[selected.status ?? "PENDING"] ?? "neutral"}>{translateBackendValue(selected.status ?? "PENDING", currentLang)}</StatusBadge></dd></div><div><dt className="text-xs font-bold text-text-secondary">{t.file}</dt><dd className="mt-1">{urlOf(selected) ? <a className="inline-flex items-center gap-1 font-bold underline" href={urlOf(selected)} rel="noreferrer" target="_blank">{t.file}<ExternalLink size={15} /></a> : t.noFile}</dd></div></dl>{selected.status === "PENDING" || !selected.status ? <div className="mt-5 flex gap-3 border-t pt-5"><button className="rounded-md bg-semantic-success px-5 py-3 text-sm font-extrabold text-white" disabled={pending} onClick={() => setDecision("approve")}>{t.approve}</button><button className="rounded-md bg-semantic-danger px-5 py-3 text-sm font-extrabold text-white" disabled={pending} onClick={() => setDecision("reject")}>{t.reject}</button></div> : null}<AdminConfirmModal isOpen={Boolean(decision)} type={decision ?? "approve"} title={decision === "approve" ? t.confirmApprove : t.confirmReject} reason={reason} onReasonChange={setReason} reasonLabel={t.reason} reasonPlaceholder={t.placeholder} cancelLabel={t.cancel} confirmLabel={t.confirm} pending={pending} onConfirm={() => void confirm()} onCancel={() => { setDecision(null); setReason(""); }} /></Surface></div> : null}
  </div>;
}
